# Generated by Django 3.2.5 on 2021-07-27 15:19

import apps.catalog.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.category.get_catalog_image_upload_path)),
                ('available', models.BooleanField(default=False, help_text='Доступны покупателям', verbose_name='Доступность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('available', models.BooleanField(default=False, help_text='Доступно для заказа', verbose_name='Доступность')),
                ('set_number', models.CharField(max_length=255, verbose_name='Артикул поставщика')),
                ('supplier_quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена поставщика')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Розничная цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('markup', models.IntegerField(help_text='Наценка для розницы', verbose_name='Наценка %')),
                ('has_rrp', models.BooleanField(default=False, help_text='Флаг наличия рекомендуемой розничной цены', verbose_name='Есть РРЦ')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_image.get_product_image_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.supplier'),
        ),
    ]
