# Generated by Django 3.2.5 on 2021-11-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shot_description',
            field=models.CharField(default='', max_length=120, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
